import AgentRootRatioBaseFaceRoundedData
import InformationTheory.CourtadeKumar.KernelCheckedBoolCommand

namespace CourtadeKumar.RootRatioBaseFaceCoverReceipts
open CourtadeKumar.RootRatioBaseFaceRoundedPilot

#kernel_checked_bool bCovered (pilot8Bounds.bCoverCheck 8)

#print axioms CourtadeKumar.RootRatioBaseFaceCoverReceipts.bCovered

end CourtadeKumar.RootRatioBaseFaceCoverReceipts
