import AgentRootRatioBaseFaceRoundedData
import InformationTheory.CourtadeKumar.KernelCheckedBoolCommand

namespace CourtadeKumar.RootRatioBaseFaceCoverReceipts
open CourtadeKumar.RootRatioBaseFaceRoundedPilot

#kernel_checked_bool cBaseCovered (pilot8Bounds.cBaseCoverCheck 8)

#print axioms CourtadeKumar.RootRatioBaseFaceCoverReceipts.cBaseCovered

end CourtadeKumar.RootRatioBaseFaceCoverReceipts
