import InformationTheory.CourtadeKumar.BSCEntropyBridge

open scoped ENNReal NNReal BigOperators

namespace CourtadeKumar

/-- Uniform average of a real-valued function on the Boolean cube. -/
noncomputable def cubeAverage (n : ℕ) (f : BitVec n → ℝ) : ℝ :=
  (2 ^ n : ℝ)⁻¹ * ∑ x, f x

lemma uniformInputPMF_toReal (n : ℕ) (x : BitVec n) :
    (uniformInputPMF n x).toReal = (2 ^ n : ℝ)⁻¹ := by
  rw [uniformInputPMF_apply, ENNReal.toReal_inv]
  norm_num

lemma bscAveragePosteriorBinaryEntropy_eq_cubeAverage
    (n : ℕ) (alpha : ℝ≥0) (halpha : alpha ≤ 1)
    (b : BitVec n → Bool) :
    bscAveragePosteriorBinaryEntropy n alpha halpha b =
      cubeAverage n (fun y ↦
        binaryEntropyBits (bscPosteriorBias n alpha halpha b y)) := by
  rw [bscAveragePosteriorBinaryEntropy, cubeAverage]
  simp_rw [uniformInputPMF_toReal, bscPosteriorBias]
  rw [Finset.mul_sum]

/-- The two posterior entropy terms generated by the final BSC output bit. -/
noncomputable def binaryEntropyPair (alpha : ℝ≥0) (A B : ℝ) : ℝ :=
  (1 / 2 : ℝ) *
      binaryEntropyBits ((1 - (alpha : ℝ)) * A + (alpha : ℝ) * B) +
    (1 / 2 : ℝ) *
      binaryEntropyBits ((alpha : ℝ) * A + (1 - (alpha : ℝ)) * B)

/-- The posterior entropy average in dimension `n + 1` is the cube average of the two-bit mixer. -/
lemma bscAveragePosteriorBinaryEntropy_succ
    (n : ℕ) (alpha : ℝ≥0) (halpha : alpha ≤ 1)
    (b : BitVec (n + 1) → Bool) :
    bscAveragePosteriorBinaryEntropy (n + 1) alpha halpha b =
      cubeAverage n (fun y ↦
        binaryEntropyPair alpha
          (bscPosteriorBias n alpha halpha (lastSection b false) y)
          (bscPosteriorBias n alpha halpha (lastSection b true) y)) := by
  rw [bscAveragePosteriorBinaryEntropy_eq_cubeAverage, cubeAverage, cubeAverage]
  have hsum :
      (∑ z : BitVec (n + 1),
        binaryEntropyBits (bscPosteriorBias (n + 1) alpha halpha b z)) =
      ∑ y : BitVec n,
        (binaryEntropyBits
            (bscPosteriorBias (n + 1) alpha halpha b (bitVecSnoc y true)) +
          binaryEntropyBits
            (bscPosteriorBias (n + 1) alpha halpha b (bitVecSnoc y false))) := by
    calc
      (∑ z : BitVec (n + 1),
          binaryEntropyBits (bscPosteriorBias (n + 1) alpha halpha b z)) =
        ∑ yd : BitVec n × Bool,
          binaryEntropyBits
            (bscPosteriorBias (n + 1) alpha halpha b (bitVecSnoc yd.1 yd.2)) := by
          apply Fintype.sum_equiv (bitVecSuccEquiv n)
          intro z
          have hz : bitVecSnoc (bitVecSuccEquiv n z).1 (bitVecSuccEquiv n z).2 = z :=
            (bitVecSuccEquiv n).symm_apply_apply z
          rw [hz]
      _ = ∑ y : BitVec n,
          (binaryEntropyBits
              (bscPosteriorBias (n + 1) alpha halpha b (bitVecSnoc y true)) +
            binaryEntropyBits
              (bscPosteriorBias (n + 1) alpha halpha b (bitVecSnoc y false))) := by
          rw [Fintype.sum_prod_type]
          apply Finset.sum_congr rfl
          intro y _
          rw [Fintype.sum_bool]
  rw [hsum]
  simp_rw [bscPosteriorBias,
    bscPosterior_true_toReal_bitVecSnoc_true,
    bscPosterior_true_toReal_bitVecSnoc_false,
    binaryEntropyPair]
  rw [pow_succ, Finset.sum_add_distrib, Finset.sum_add_distrib]
  rw [← Finset.mul_sum, ← Finset.mul_sum]
  field_simp
  ring

/-- The unconditional probability that the Boolean function equals `true`. -/
noncomputable def bscPriorBias (n : ℕ) (b : BitVec n → Bool) : ℝ :=
  (((uniformInputPMF n).map b) true).toReal

/-- The prior bias is the uniform cube average of the Boolean indicator. -/
lemma bscPriorBias_eq_cubeAverage (n : ℕ) (b : BitVec n → Bool) :
    bscPriorBias n b = cubeAverage n (fun x ↦ if b x then 1 else 0) := by
  rw [bscPriorBias, PMF.map_apply, tsum_fintype]
  rw [ENNReal.toReal_sum]
  · rw [cubeAverage]
    rw [Finset.mul_sum]
    apply Finset.sum_congr rfl
    intro x _
    cases b x <;> simp
  · intro x _
    split <;> simp

/-- The prior bias in dimension `n + 1` is the mean of the two section biases. -/
lemma bscPriorBias_succ (n : ℕ) (b : BitVec (n + 1) → Bool) :
    bscPriorBias (n + 1) b =
      (bscPriorBias n (lastSection b false) +
        bscPriorBias n (lastSection b true)) / 2 := by
  rw [bscPriorBias_eq_cubeAverage, bscPriorBias_eq_cubeAverage,
    bscPriorBias_eq_cubeAverage]
  rw [cubeAverage, cubeAverage, cubeAverage]
  have hsum :
      (∑ z : BitVec (n + 1), (if b z then (1 : ℝ) else 0)) =
        ∑ y : BitVec n,
          ((if b (bitVecSnoc y true) then (1 : ℝ) else 0) +
            (if b (bitVecSnoc y false) then (1 : ℝ) else 0)) := by
    calc
      (∑ z : BitVec (n + 1), (if b z then (1 : ℝ) else 0)) =
        ∑ yd : BitVec n × Bool,
          (if b (bitVecSnoc yd.1 yd.2) then (1 : ℝ) else 0) := by
            apply Fintype.sum_equiv (bitVecSuccEquiv n)
            intro z
            have hz : bitVecSnoc (bitVecSuccEquiv n z).1 (bitVecSuccEquiv n z).2 = z :=
              (bitVecSuccEquiv n).symm_apply_apply z
            rw [hz]
      _ = ∑ y : BitVec n,
          ((if b (bitVecSnoc y true) then (1 : ℝ) else 0) +
            (if b (bitVecSnoc y false) then (1 : ℝ) else 0)) := by
            rw [Fintype.sum_prod_type]
            apply Finset.sum_congr rfl
            intro y _
            rw [Fintype.sum_bool]
  rw [hsum, pow_succ, Finset.sum_add_distrib]
  simp only [lastSection]
  field_simp
  ring

lemma bscPosteriorBias_nonneg
    (n : ℕ) (alpha : ℝ≥0) (halpha : alpha ≤ 1)
    (b : BitVec n → Bool) (y : BitVec n) :
    0 ≤ bscPosteriorBias n alpha halpha b y :=
  ENNReal.toReal_nonneg

lemma bscPosteriorBias_le_one
    (n : ℕ) (alpha : ℝ≥0) (halpha : alpha ≤ 1)
    (b : BitVec n → Bool) (y : BitVec n) :
    bscPosteriorBias n alpha halpha b y ≤ 1 := by
  exact (ENNReal.toReal_le_toReal
    ((bscPosteriorPMF n alpha halpha b y).apply_ne_top true)
    ENNReal.one_ne_top).2 ((bscPosteriorPMF n alpha halpha b y).coe_le_one true)

/-- Averaging the posterior bias recovers the prior bias. -/
lemma cubeAverage_bscPosteriorBias
    (n : ℕ) (alpha : ℝ≥0) (halpha : alpha ≤ 1)
    (b : BitVec n → Bool) :
    cubeAverage n (bscPosteriorBias n alpha halpha b) = bscPriorBias n b := by
  rw [bscPriorBias]
  have hfst := bscJointPMF_map_fst n alpha halpha b
  have hatom := congrArg (fun p : PMF Bool ↦ (p true).toReal) hfst
  change (((bscJointPMF n alpha halpha b).map Prod.fst) true).toReal =
    (((uniformInputPMF n).map b) true).toReal at hatom
  rw [map_fst_toReal_eq_sum] at hatom
  simp_rw [bscJointPMF_eq_output_mul_posterior, ENNReal.toReal_mul,
    uniformInputPMF_toReal] at hatom
  rw [cubeAverage, Finset.mul_sum]
  simpa [bscPosteriorBias] using hatom

/-- The channel correlation parameter `1 - 2 alpha`. -/
noncomputable def channelRho (alpha : ℝ) : ℝ :=
  1 - 2 * alpha

/-- The complementary squared correlation `1 - rho^2`. -/
noncomputable def channelS (alpha : ℝ) : ℝ :=
  1 - channelRho alpha ^ 2

/-- The equal-multiplier coefficient in the Bellman envelope. -/
noncomputable def bellmanLambda (alpha : ℝ) : ℝ :=
  binaryEntropyBits alpha - channelS alpha

/-- The scalar Bellman envelope used in the Boolean induction. -/
noncomputable def bellmanEnvelope (alpha p : ℝ) : ℝ :=
  channelS alpha * binaryEntropyBits p +
    4 * bellmanLambda alpha * p * (1 - p)

/-- The exact scalar implication needed at each Boolean induction step. -/
def BooleanBellmanStep (alpha : ℝ≥0) : Prop :=
  ∀ (n : ℕ) (A B : BitVec n → ℝ),
    (∀ y, 0 ≤ A y ∧ A y ≤ 1) →
    (∀ y, 0 ≤ B y ∧ B y ≤ 1) →
    cubeAverage n (fun y ↦ binaryEntropyBits (A y)) ≥
        bellmanEnvelope (alpha : ℝ) (cubeAverage n A) →
    cubeAverage n (fun y ↦ binaryEntropyBits (B y)) ≥
        bellmanEnvelope (alpha : ℝ) (cubeAverage n B) →
    cubeAverage n (fun y ↦ binaryEntropyPair alpha (A y) (B y)) ≥
      bellmanEnvelope (alpha : ℝ)
        ((cubeAverage n A + cubeAverage n B) / 2)

lemma bellmanEnvelope_zero (alpha : ℝ) : bellmanEnvelope alpha 0 = 0 := by
  simp [bellmanEnvelope, binaryEntropyBits, Real.binEntropy]

lemma bellmanEnvelope_one (alpha : ℝ) : bellmanEnvelope alpha 1 = 0 := by
  simp [bellmanEnvelope, binaryEntropyBits, Real.binEntropy]

private lemma ennrealIndicator_toReal (q : Prop) [Decidable q] :
    (if q then (1 : ℝ≥0∞) else 0).toReal =
      if q then (1 : ℝ) else 0 := by
  by_cases h : q <;> simp [h]

private lemma trueEqBoolIndicator (v : Bool) :
    (if true = v then (1 : ℝ) else 0) = if v then 1 else 0 := by
  cases v <;> norm_num

lemma bscPriorBias_zero (b : BitVec 0 → Bool) :
    bscPriorBias 0 b = if b (fun _ ↦ false) then 1 else 0 := by
  rw [bscPriorBias_eq_cubeAverage, cubeAverage, Fintype.sum_unique]
  norm_num
  exact congrArg (fun v : Bool ↦ if v then (1 : ℝ) else 0)
    (congrArg b (Subsingleton.elim _ _))

lemma bscPosteriorBias_zero
    (alpha : ℝ≥0) (halpha : alpha ≤ 1)
    (b : BitVec 0 → Bool) (y : BitVec 0) :
    bscPosteriorBias 0 alpha halpha b y =
      if b (fun _ ↦ false) then 1 else 0 := by
  rw [bscPosteriorBias, bscPosteriorPMF_apply, Fintype.sum_unique]
  simp only [iidBernoulliPMF_apply, Fin.prod_univ_zero]
  let x₀ : BitVec 0 := @default (BitVec 0) Unique.instInhabited
  change (if true = b x₀ then (1 : ℝ≥0∞) else 0).toReal =
    if b (fun _ ↦ false) then (1 : ℝ) else 0
  have hb : b x₀ = b (fun _ ↦ false) :=
    congrArg b (Subsingleton.elim _ _)
  calc
    (if true = b x₀ then (1 : ℝ≥0∞) else 0).toReal =
        (if true = b x₀ then (1 : ℝ) else 0) :=
      ennrealIndicator_toReal (true = b x₀)
    _ = if b x₀ then (1 : ℝ) else 0 := trueEqBoolIndicator (b x₀)
    _ = if b (fun _ ↦ false) then (1 : ℝ) else 0 :=
      congrArg (fun v : Bool ↦ if v then (1 : ℝ) else 0) hb

lemma bscAveragePosteriorBinaryEntropy_zero
    (alpha : ℝ≥0) (halpha : alpha ≤ 1)
    (b : BitVec 0 → Bool) :
    bscAveragePosteriorBinaryEntropy 0 alpha halpha b = 0 := by
  rw [bscAveragePosteriorBinaryEntropy_eq_cubeAverage, cubeAverage,
    Fintype.sum_unique, bscPosteriorBias_zero]
  cases b (fun _ ↦ false) <;> simp [binaryEntropyBits, Real.binEntropy]

/-- Once the scalar Bellman step is available, the posterior-entropy lower bound
follows for every Boolean function by splitting off the final cube coordinate. -/
theorem bscAveragePosteriorBinaryEntropy_ge_bellmanEnvelope_of_step
    (alpha : ℝ≥0) (halpha : alpha ≤ 1)
    (hBellman : BooleanBellmanStep alpha) :
    ∀ (n : ℕ) (b : BitVec n → Bool),
      bscAveragePosteriorBinaryEntropy n alpha halpha b ≥
        bellmanEnvelope (alpha : ℝ) (bscPriorBias n b) := by
  intro n
  induction n with
  | zero =>
      intro b
      rw [bscAveragePosteriorBinaryEntropy_zero, bscPriorBias_zero]
      cases h : b (fun _ ↦ false)
      · simp [bellmanEnvelope_zero]
      · simp [bellmanEnvelope_one]
  | succ n ih =>
      intro b
      let A : BitVec n → ℝ :=
        bscPosteriorBias n alpha halpha (lastSection b false)
      let B : BitVec n → ℝ :=
        bscPosteriorBias n alpha halpha (lastSection b true)
      have hA_bound : ∀ y, 0 ≤ A y ∧ A y ≤ 1 := by
        intro y
        exact ⟨bscPosteriorBias_nonneg n alpha halpha _ y,
          bscPosteriorBias_le_one n alpha halpha _ y⟩
      have hB_bound : ∀ y, 0 ≤ B y ∧ B y ≤ 1 := by
        intro y
        exact ⟨bscPosteriorBias_nonneg n alpha halpha _ y,
          bscPosteriorBias_le_one n alpha halpha _ y⟩
      have hA_entropy :
          cubeAverage n (fun y ↦ binaryEntropyBits (A y)) ≥
            bellmanEnvelope (alpha : ℝ) (cubeAverage n A) := by
        simpa [A, bscAveragePosteriorBinaryEntropy_eq_cubeAverage,
          cubeAverage_bscPosteriorBias] using
          ih (lastSection b false)
      have hB_entropy :
          cubeAverage n (fun y ↦ binaryEntropyBits (B y)) ≥
            bellmanEnvelope (alpha : ℝ) (cubeAverage n B) := by
        simpa [B, bscAveragePosteriorBinaryEntropy_eq_cubeAverage,
          cubeAverage_bscPosteriorBias] using
          ih (lastSection b true)
      have hstep := hBellman n A B hA_bound hB_bound hA_entropy hB_entropy
      rw [bscAveragePosteriorBinaryEntropy_succ, bscPriorBias_succ]
      simpa [A, B, cubeAverage_bscPosteriorBias] using hstep

end CourtadeKumar
