import InformationTheory.CourtadeKumar.IntervalSubdivisionCertificateCore
import Mathlib.Data.Rat.Cast.Order
import Mathlib.Data.Real.Basic

/-!
# Kernel-checked subdivision certificates

This file provides the structural layer of the exact interval certificates
used in the high-shape LR argument.  Certificate data may be generated by an
untrusted external program.  The checker reconstructs every child box from
its parent, so certificate data cannot silently change the region being
proved.

The analytic leaf checker and the physical-domain discard checker are kept
abstract here.  `subdivisionCertificate_sound` shows that sound leaf
checkers, together with a successful Boolean traversal, prove the desired
property at every relevant point of the root box.
-/

namespace CourtadeKumar

/-- A point in the three cancellation coordinates `(s, k, χ)`. -/
structure CertificatePoint where
  s : ℝ
  k : ℝ
  chi : ℝ

/-- A real number lies in a rational enclosure. -/
def RationalEnclosure.Contains (interval : RationalEnclosure) (x : ℝ) : Prop :=
  (interval.lower : ℝ) ≤ x ∧ x ≤ (interval.upper : ℝ)

theorem RationalEnclosure.nonnegative_of_provesNonnegative
    {interval : RationalEnclosure} {x : ℝ}
    (hcheck : interval.provesNonnegative = true)
    (hx : interval.Contains x) :
    0 ≤ x := by
  have hlower : (0 : ℚ) ≤ interval.lower := by
    simpa [RationalEnclosure.provesNonnegative] using hcheck
  exact le_trans (by exact_mod_cast hlower) hx.1

/-- Membership in a rational certificate box, interpreted over the reals. -/
def CertificateBox.Contains (box : CertificateBox)
    (point : CertificatePoint) : Prop :=
  (box.sLo : ℝ) ≤ point.s ∧ point.s ≤ (box.sHi : ℝ) ∧
  (box.kLo : ℝ) ≤ point.k ∧ point.k ≤ (box.kHi : ℝ) ∧
  (box.chiLo : ℝ) ≤ point.chi ∧ point.chi ≤ (box.chiHi : ℝ)

theorem CertificateBox.contains_lower_or_upper
    {box : CertificateBox} {point : CertificatePoint}
    (hpoint : box.Contains point) (axis : CertificateAxis) (cut : ℚ) :
    (box.lower axis cut).Contains point ∨
      (box.upper axis cut).Contains point := by
  rcases hpoint with ⟨hsLo, hsHi, hkLo, hkHi, hchiLo, hchiHi⟩
  cases axis with
  | s =>
      rcases le_total point.s (cut : ℝ) with hs | hs
      · exact Or.inl ⟨hsLo, hs, hkLo, hkHi, hchiLo, hchiHi⟩
      · exact Or.inr ⟨hs, hsHi, hkLo, hkHi, hchiLo, hchiHi⟩
  | k =>
      rcases le_total point.k (cut : ℝ) with hk | hk
      · exact Or.inl ⟨hsLo, hsHi, hkLo, hk, hchiLo, hchiHi⟩
      · exact Or.inr ⟨hsLo, hsHi, hk, hkHi, hchiLo, hchiHi⟩
  | chi =>
      rcases le_total point.chi (cut : ℝ) with hchi | hchi
      · exact Or.inl ⟨hsLo, hsHi, hkLo, hkHi, hchiLo, hchi⟩
      · exact Or.inr ⟨hsLo, hsHi, hkLo, hkHi, hchi, hchiHi⟩

theorem SubdivisionCertificate.check_eq_coreCheck
    {AcceptData DiscardData : Type}
    (acceptBox : CertificateBox → AcceptData → Bool)
    (discardBox : CertificateBox → DiscardData → Bool)
    (box : CertificateBox)
    (certificate : SubdivisionCertificate AcceptData DiscardData) :
    certificate.check acceptBox discardBox box =
      certificate.coreCheck acceptBox discardBox box := rfl

/-- Soundness of the generic subdivision checker.  The external generator
is absent from the theorem's assumptions: only the two verified leaf
implications and the result of the Boolean checker matter. -/
theorem subdivisionCertificate_sound
    {Relevant Property : CertificatePoint → Prop}
    {AcceptData DiscardData : Type}
    {acceptBox : CertificateBox → AcceptData → Bool}
    {discardBox : CertificateBox → DiscardData → Bool}
    (accept_sound : ∀ box data, acceptBox box data = true →
      ∀ point, box.Contains point → Property point)
    (discard_sound : ∀ box data, discardBox box data = true →
      ∀ point, box.Contains point → ¬ Relevant point)
    {box : CertificateBox}
    {certificate : SubdivisionCertificate AcceptData DiscardData}
    (hcheck : certificate.check acceptBox discardBox box = true) :
    ∀ point, box.Contains point → Relevant point → Property point := by
  induction certificate generalizing box with
  | accept data =>
      intro point hpoint _
      exact accept_sound box data
        (by simpa [SubdivisionCertificate.check] using hcheck)
        point hpoint
  | discard data =>
      intro point hpoint hRelevant
      have hdiscard : discardBox box data = true := by
        simpa [SubdivisionCertificate.check] using hcheck
      exact (discard_sound box data hdiscard point hpoint hRelevant).elim
  | split axis cut lower upper lower_ih upper_ih =>
      have hchildren := Bool.and_eq_true_iff.mp
        (by simpa [SubdivisionCertificate.check] using hcheck)
      intro point hpoint hRelevant
      rcases box.contains_lower_or_upper hpoint axis cut with hLower | hUpper
      · exact lower_ih hchildren.1 point hLower hRelevant
      · exact upper_ih hchildren.2 point hUpper hRelevant

/-- The proof-free core check can be passed directly to the established
semantic checker theorem. -/
theorem subdivisionCertificate_sound_of_coreCheck
    {Relevant Property : CertificatePoint → Prop}
    {AcceptData DiscardData : Type}
    {acceptBox : CertificateBox → AcceptData → Bool}
    {discardBox : CertificateBox → DiscardData → Bool}
    (accept_sound : ∀ box data, acceptBox box data = true →
      ∀ point, box.Contains point → Property point)
    (discard_sound : ∀ box data, discardBox box data = true →
      ∀ point, box.Contains point → ¬ Relevant point)
    {box : CertificateBox}
    {certificate : SubdivisionCertificate AcceptData DiscardData}
    (hcheck : certificate.coreCheck acceptBox discardBox box = true) :
    ∀ point, box.Contains point → Relevant point → Property point := by
  apply subdivisionCertificate_sound accept_sound discard_sound
  simpa only [SubdivisionCertificate.check_eq_coreCheck] using hcheck

/-- End-to-end structural soundness for nonnegativity certificates.  What
remains for a concrete target is to prove that `enclose` contains the target
throughout each box and that every accepted discard excludes the physical
domain. -/
theorem subdivisionCertificate_nonnegative
    {Relevant : CertificatePoint → Prop}
    {target : CertificatePoint → ℝ}
    {AcceptData DiscardData : Type}
    {enclose : CertificateBox → AcceptData → RationalEnclosure}
    {discardBox : CertificateBox → DiscardData → Bool}
    (enclose_sound : ∀ box data point, box.Contains point →
      (enclose box data).Contains (target point))
    (discard_sound : ∀ box data, discardBox box data = true →
      ∀ point, box.Contains point → ¬ Relevant point)
    {box : CertificateBox}
    {certificate : SubdivisionCertificate AcceptData DiscardData}
    (hcheck : certificate.check (enclosureAccepts enclose) discardBox box = true) :
    ∀ point, box.Contains point → Relevant point → 0 ≤ target point := by
  apply subdivisionCertificate_sound
      (Relevant := Relevant) (Property := fun point ↦ 0 ≤ target point)
      (acceptBox := enclosureAccepts enclose) (discardBox := discardBox)
      (box := box) (certificate := certificate) ?_ discard_sound hcheck
  intro leaf data hleaf point hpoint
  exact RationalEnclosure.nonnegative_of_provesNonnegative hleaf
    (enclose_sound leaf data point hpoint)

end CourtadeKumar
