import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch0
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch1
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch2
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch3
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch4
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch5
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch6
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch7
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch8
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch9
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch10
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch11
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch12
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch13
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch14
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch15
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch16
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch17
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch18
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch19
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch20
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch21
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch22
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch23
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch24
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch25
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch26
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch27
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch28
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch29
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch30
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch31
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch32
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch33
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch34
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch35
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch36
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch37
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch38
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch39
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch40
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch41
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch42
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch43
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch44
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch45
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch46
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch47
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch48
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch49
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch50
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch51
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch52
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch53
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch54
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch55
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch56
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch57
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch58
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch59
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch60
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch61
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch62
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch63
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch64
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch65
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch66
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch67
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch68
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch69
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch70
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch71
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch72
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch73
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch74
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch75
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch76
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch77
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch78
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch79
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch80
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch81
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch82
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch83
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch84
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch85
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch86
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch87
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch88
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch89
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch90
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch91
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch92
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch93
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch94
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch95
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch96
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch97
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch98
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch99
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch100
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch101
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch102
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch103
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch104
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch105
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch106
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch107
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch108
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch109
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch110
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch111
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch112
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch113
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch114
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch115
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch116
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch117
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch118
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch119
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch120
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch121
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch122
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch123
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch124
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch125
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch126
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch127
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch128
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch129
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch130
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch131
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch132
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch133
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch134
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch135
import InformationTheory.CourtadeKumar.LRGapBudgetSEGeneratedTailReplayBatch136

namespace CourtadeKumar
namespace LRGapBudgetSEGeneratedTailReplay

open LRGapBudgetSECombinedAutoTree

def tree : Tree :=
  (.split .s (1/100) (.split .s (1/1000) (.split .s (1/10000) (.split .s (1/100000) (.split .k (1/2) chunk0 (.split .chi (1/2) (.split .k (3/4) chunk1 chunk2) chunk3)) (.split .k (1/2) chunk4 (.split .chi (1/2) (.split .k (3/4) chunk5 chunk6) chunk7))) (.split .k (1/2) chunk8 (.split .chi (1/2) (.split .k (3/4) chunk9 chunk10) chunk11))) (.split .k (1/2) chunk12 (.split .chi (1/2) (.split .k (3/4) chunk13 (.split .chi (1/4) (.split .k (7/8) chunk14 (.split .chi (1/8) (.split .k (15/16) (.split .chi (1/16) chunk15 chunk16) chunk17) (.split .k (15/16) (.split .chi (3/16) (.split .s (11/2000) chunk18 chunk19) chunk20) chunk21))) chunk22)) chunk23))) (.split .k (1/2) (.split .chi (1/2) (.split .s (11/200) chunk24 chunk25) chunk26) (.split .chi (1/2) (.split .s (11/200) (.split .k (3/4) (.split .chi (1/4) (.split .s (13/400) chunk27 (.split .k (5/8) chunk28 chunk29)) chunk30) (.split .chi (1/4) (.split .s (13/400) (.split .k (7/8) (.split .chi (1/8) (.split .s (17/800) (.split .k (13/16) chunk31 (.split .chi (1/16) chunk32 chunk33)) (.split .k (13/16) chunk34 (.split .chi (1/16) chunk35 chunk36))) (.split .s (17/800) chunk37 (.split .k (13/16) chunk38 chunk39))) (.split .chi (1/8) (.split .s (17/800) (.split .k (15/16) (.split .chi (1/16) chunk40 chunk41) chunk42) (.split .k (15/16) (.split .chi (1/16) chunk43 chunk44) chunk45)) (.split .s (17/800) (.split .k (15/16) (.split .chi (3/16) (.split .s (1/64) chunk46 chunk47) chunk48) chunk49) (.split .k (15/16) (.split .chi (3/16) (.split .s (43/1600) chunk50 chunk51) chunk52) chunk53)))) (.split .k (7/8) (.split .chi (1/8) (.split .s (7/160) (.split .k (13/16) chunk54 (.split .chi (1/16) chunk55 chunk56)) (.split .k (13/16) chunk57 (.split .chi (1/16) chunk58 chunk59))) (.split .s (7/160) (.split .k (13/16) chunk60 chunk61) (.split .k (13/16) chunk62 chunk63))) (.split .chi (1/8) (.split .s (7/160) (.split .k (15/16) (.split .chi (1/16) chunk64 (.split .s (61/1600) chunk65 chunk66)) chunk67) (.split .k (15/16) (.split .chi (1/16) (.split .s (79/1600) chunk68 chunk69) (.split .s (79/1600) chunk70 chunk71)) chunk72)) (.split .s (7/160) (.split .k (15/16) (.split .chi (3/16) (.split .s (61/1600) chunk73 chunk74) chunk75) chunk76) (.split .k (15/16) (.split .chi (3/16) (.split .s (79/1600) chunk77 chunk78) chunk79) chunk80))))) chunk81)) (.split .k (3/4) (.split .chi (1/4) (.split .s (31/400) chunk82 chunk83) chunk84) (.split .chi (1/4) (.split .s (31/400) (.split .k (7/8) (.split .chi (1/8) (.split .s (53/800) (.split .k (13/16) chunk85 (.split .chi (1/16) chunk86 chunk87)) (.split .k (13/16) chunk88 (.split .chi (1/16) chunk89 chunk90))) (.split .s (53/800) (.split .k (13/16) chunk91 chunk92) (.split .k (13/16) chunk93 chunk94))) (.split .chi (1/8) (.split .s (53/800) (.split .k (15/16) (.split .chi (1/16) chunk95 (.split .s (97/1600) chunk96 chunk97)) chunk98) (.split .k (15/16) (.split .chi (1/16) chunk99 chunk100) chunk101)) (.split .s (53/800) (.split .k (15/16) (.split .chi (3/16) (.split .s (97/1600) chunk102 chunk103) chunk104) chunk105) (.split .k (15/16) (.split .chi (3/16) (.split .s (23/320) chunk106 chunk107) chunk108) chunk109)))) (.split .k (7/8) (.split .chi (1/8) (.split .s (71/800) (.split .k (13/16) chunk110 (.split .chi (1/16) chunk111 chunk112)) (.split .k (13/16) chunk113 (.split .chi (1/16) chunk114 chunk115))) (.split .s (71/800) (.split .k (13/16) chunk116 chunk117) (.split .k (13/16) chunk118 chunk119))) (.split .chi (1/8) (.split .s (71/800) (.split .k (15/16) (.split .chi (1/16) chunk120 chunk121) chunk122) (.split .k (15/16) (.split .chi (1/16) chunk123 (.split .s (151/1600) chunk124 chunk125)) chunk126)) (.split .s (71/800) (.split .k (15/16) (.split .chi (3/16) (.split .s (133/1600) chunk127 chunk128) chunk129) chunk130) (.split .k (15/16) (.split .chi (3/16) (.split .s (151/1600) chunk131 chunk132) chunk133) chunk134))))) chunk135))) chunk136)))

set_option maxRecDepth 1000000 in
theorem check_eq_true :
    tree.check
      (LRGapBudgetSEDerivativeAcceptData.check 2 8 6)
      lrGapBudgetSEDiscardCheck lrGapBudgetSETailRoot = true := by
  simp only [tree, SubdivisionCertificate.check, Bool.and_eq_true]
  exact ⟨⟨⟨⟨⟨chunk0_check, ⟨⟨chunk1_check, chunk2_check⟩, chunk3_check⟩⟩, ⟨chunk4_check, ⟨⟨chunk5_check, chunk6_check⟩, chunk7_check⟩⟩⟩, ⟨chunk8_check, ⟨⟨chunk9_check, chunk10_check⟩, chunk11_check⟩⟩⟩, ⟨chunk12_check, ⟨⟨chunk13_check, ⟨⟨chunk14_check, ⟨⟨⟨chunk15_check, chunk16_check⟩, chunk17_check⟩, ⟨⟨⟨chunk18_check, chunk19_check⟩, chunk20_check⟩, chunk21_check⟩⟩⟩, chunk22_check⟩⟩, chunk23_check⟩⟩⟩, ⟨⟨⟨chunk24_check, chunk25_check⟩, chunk26_check⟩, ⟨⟨⟨⟨⟨chunk27_check, ⟨chunk28_check, chunk29_check⟩⟩, chunk30_check⟩, ⟨⟨⟨⟨⟨⟨chunk31_check, ⟨chunk32_check, chunk33_check⟩⟩, ⟨chunk34_check, ⟨chunk35_check, chunk36_check⟩⟩⟩, ⟨chunk37_check, ⟨chunk38_check, chunk39_check⟩⟩⟩, ⟨⟨⟨⟨chunk40_check, chunk41_check⟩, chunk42_check⟩, ⟨⟨chunk43_check, chunk44_check⟩, chunk45_check⟩⟩, ⟨⟨⟨⟨chunk46_check, chunk47_check⟩, chunk48_check⟩, chunk49_check⟩, ⟨⟨⟨chunk50_check, chunk51_check⟩, chunk52_check⟩, chunk53_check⟩⟩⟩⟩, ⟨⟨⟨⟨chunk54_check, ⟨chunk55_check, chunk56_check⟩⟩, ⟨chunk57_check, ⟨chunk58_check, chunk59_check⟩⟩⟩, ⟨⟨chunk60_check, chunk61_check⟩, ⟨chunk62_check, chunk63_check⟩⟩⟩, ⟨⟨⟨⟨chunk64_check, ⟨chunk65_check, chunk66_check⟩⟩, chunk67_check⟩, ⟨⟨⟨chunk68_check, chunk69_check⟩, ⟨chunk70_check, chunk71_check⟩⟩, chunk72_check⟩⟩, ⟨⟨⟨⟨chunk73_check, chunk74_check⟩, chunk75_check⟩, chunk76_check⟩, ⟨⟨⟨chunk77_check, chunk78_check⟩, chunk79_check⟩, chunk80_check⟩⟩⟩⟩⟩, chunk81_check⟩⟩, ⟨⟨⟨chunk82_check, chunk83_check⟩, chunk84_check⟩, ⟨⟨⟨⟨⟨⟨chunk85_check, ⟨chunk86_check, chunk87_check⟩⟩, ⟨chunk88_check, ⟨chunk89_check, chunk90_check⟩⟩⟩, ⟨⟨chunk91_check, chunk92_check⟩, ⟨chunk93_check, chunk94_check⟩⟩⟩, ⟨⟨⟨⟨chunk95_check, ⟨chunk96_check, chunk97_check⟩⟩, chunk98_check⟩, ⟨⟨chunk99_check, chunk100_check⟩, chunk101_check⟩⟩, ⟨⟨⟨⟨chunk102_check, chunk103_check⟩, chunk104_check⟩, chunk105_check⟩, ⟨⟨⟨chunk106_check, chunk107_check⟩, chunk108_check⟩, chunk109_check⟩⟩⟩⟩, ⟨⟨⟨⟨chunk110_check, ⟨chunk111_check, chunk112_check⟩⟩, ⟨chunk113_check, ⟨chunk114_check, chunk115_check⟩⟩⟩, ⟨⟨chunk116_check, chunk117_check⟩, ⟨chunk118_check, chunk119_check⟩⟩⟩, ⟨⟨⟨⟨chunk120_check, chunk121_check⟩, chunk122_check⟩, ⟨⟨chunk123_check, ⟨chunk124_check, chunk125_check⟩⟩, chunk126_check⟩⟩, ⟨⟨⟨⟨chunk127_check, chunk128_check⟩, chunk129_check⟩, chunk130_check⟩, ⟨⟨⟨chunk131_check, chunk132_check⟩, chunk133_check⟩, chunk134_check⟩⟩⟩⟩⟩, chunk135_check⟩⟩⟩, chunk136_check⟩⟩⟩

end LRGapBudgetSEGeneratedTailReplay
end CourtadeKumar
