import InformationTheory.CourtadeKumar.LRLowShapeUL1Monotone

/-! Exact univariate Bernstein closure of the low-shape `L₁` base case.
The coefficients are generated by
`scripts/generate_lr_lowshape_l1_data.py`; that standard-library replay also
checks the original degree `(41,12)` tensor certificate from the manuscript. -/

open Set

namespace CourtadeKumar

noncomputable def lrLowL1Base (v : ℝ) : ℝ :=
  (1 + v) ^ 9 * (2 + v) ^ 9

noncomputable def lrLowL1EndpointBernstein (v : ℝ) : ℝ :=
  (336272743530427664525174617069/19377092109375000000) * bernsteinBasis 40 0 v +
  (65575467870107415297307492578707/3100334737500000000000) * bernsteinBasis 40 1 v +
  (224305048671081575367305412707029/8636646768750000000000) * bernsteinBasis 40 2 v +
  (98291028395433112311360502735545763/3063130720650000000000000) * bernsteinBasis 40 3 v +
  (70563761705166141462371661100076021/1770872447875781250000000) * bernsteinBasis 40 4 v +
  (10134864874385539741724541393474768871/204004505995290000000000000) * bernsteinBasis 40 5 v +
  (24645267808140320250240067476961068373/396675428324175000000000000) * bernsteinBasis 40 6 v +
  (1200361028998863118582239026506963105501/15413673786310800000000000000) * bernsteinBasis 40 7 v +
  (731328239686313608907057280792629419223/7480165219827300000000000000) * bernsteinBasis 40 8 v +
  (7325493284498785535871588577171290150481/59622122777817600000000000000) * bernsteinBasis 40 9 v +
  (519654560150977164568860154228903772394511/3363880167124468992000000000000) * bernsteinBasis 40 10 v +
  (8910277872896274255394639273773621899068273/45871093188060940800000000000000) * bernsteinBasis 40 11 v +
  (27068446496345567049317701545121729720369783/110855141871147273600000000000000) * bernsteinBasis 40 12 v +
  (2929798394519651075296213528090787071371119/9550596838129611264000000000000) * bernsteinBasis 40 13 v +
  (10430236954825544120607287548453177529488253/27086776746796166400000000000000) * bernsteinBasis 40 14 v +
  (3293814357303253236754095942218519473302379/6821854884378293760000000000000) * bernsteinBasis 40 15 v +
  (3989744610192299716802052136495978136146129/6598520349473052000000000000000) * bernsteinBasis 40 16 v +
  (36976991527433760087076782882171443512829957/48906680237270856000000000000000) * bernsteinBasis 40 17 v +
  (1061731386082773018926479593384730317558876847/1124853645457229688000000000000000) * bernsteinBasis 40 18 v +
  (360049102799477060116349280176075503195643/306101554827868800000000000000) * bernsteinBasis 40 19 v +
  (2999570991217176878227000286062622935481209/2050352656045293600000000000000) * bernsteinBasis 40 20 v +
  (14689136897321589894388390480440281680494479/8089826806165104000000000000000) * bernsteinBasis 40 21 v +
  (3792102202747216784361566183502674985858887/1686437249561064000000000000000) * bernsteinBasis 40 22 v +
  (188112461929136846808293764649650460082753391/67716941866990416000000000000000) * bernsteinBasis 40 23 v +
  (142298888537329344555132549579514871407188281/41570678201680227600000000000000) * bernsteinBasis 40 24 v +
  (13166160675224961318862217948219096422004509/3130027535185334784000000000000) * bernsteinBasis 40 25 v +
  (791048435430539002241018607531674929988610173/153491734898511609600000000000000) * bernsteinBasis 40 26 v +
  (2404472567699382816678220957103155163779013/382023873525184450560000000000) * bernsteinBasis 40 27 v +
  (77193743592428261742088410507884198335676249/10077740170104297600000000000000) * bernsteinBasis 40 28 v +
  (425965126185144621280162663264936532743959131/45871093188060940800000000000000) * bernsteinBasis 40 29 v +
  (17139869483247808225149683865560082398828659/1529036439602031360000000000000) * bernsteinBasis 40 30 v +
  (4297799119004202822497494457383076769554867/319153716045964800000000000000) * bernsteinBasis 40 31 v +
  (2454933553551136072165023200909428839614657/152595370484476920000000000000) * bernsteinBasis 40 32 v +
  (16352108015291038396623406698504200562967/856315210350600000000000000) * bernsteinBasis 40 33 v +
  (7509918756802910247258090969761914211/333901875693750000000000) * bernsteinBasis 40 34 v +
  (132168107984535665523315705852492320813/5037148296180000000000000) * bernsteinBasis 40 35 v +
  (1511059014969230334746958482884920381/49971709287500000000000) * bernsteinBasis 40 36 v +
  (7045627167956660411569437375615531/205524068750000000000) * bernsteinBasis 40 37 v +
  (9446452249451216064587668565217873/248792293750000000000) * bernsteinBasis 40 38 v +
  (1552766591198803834191751436290203/38275737500000000000) * bernsteinBasis 40 39 v +
  (1771272191201562445262327273151/43495156250000000) * bernsteinBasis 40 40 v

lemma lrLowL1EndpointBernstein_nonneg
    {v : ℝ} (hv : v ∈ Icc (0 : ℝ) 1) :
    0 ≤ lrLowL1EndpointBernstein v := by
  unfold lrLowL1EndpointBernstein
  repeat' apply add_nonneg
  all_goals exact mul_nonneg (by norm_num) (bernsteinBasis_nonneg hv)

set_option maxHeartbeats 10000000 in
lemma lrLowL1_endpoint_difference_identity
    {v : ℝ} (hv : v ∈ Ioc (0 : ℝ) 1) :
    (lrLowL1Minorant v lrLowShapeX -
        lrLowL1Minorant 1 lrLowShapeX) *
          lrLowL1Base v * lrLowL1Base 1 =
      (1 - v) * lrLowL1EndpointBernstein v := by
  have h1 : 1 + v ≠ 0 := by linarith [hv.1]
  have h2 : 2 + v ≠ 0 := by linarith [hv.1]
  have h4 : 4 + 4 * v ≠ 0 := by linarith [hv.1]
  have hvClosed : v ∈ Icc (0 : ℝ) 1 := ⟨hv.1.le, hv.2⟩
  have hy := lrBetaRatio_mem_Icc hvClosed
  have hyden : 1 - (v / (2 + v)) ^ 2 ≠ 0 := by
    nlinarith [hy.1, hy.2]
  have hyidentity : 1 - (v / (2 + v)) ^ 2 =
      (4 + 4 * v) / (2 + v) ^ 2 := by
    field_simp [h2]
    ring
  unfold lrLowL1Minorant lrLowL1Base lrLowGLower lrLowBetaLower
    lrLowMinusLogLower lrLowP1Lower lrLowB1Upper lrLowTailH lrFlowM
    lrAtanh5Upper lrAtanh5 lrLowShapeX lrLowL1EndpointBernstein
    bernsteinBasis lrLowA lrLowT
  rw [hyidentity]
  norm_num [Finset.sum_range_succ, Nat.choose]
  field_simp [hv.1.ne', h1, h2, h4, hyden]
  ring

lemma lrLowL1Minorant_one_edge_pos :
    0 < lrLowL1Minorant 1 lrLowShapeX := by
  norm_num [lrLowL1Minorant, lrLowGLower, lrLowBetaLower,
    lrLowMinusLogLower, lrLowP1Lower, lrLowB1Upper, lrLowTailH,
    lrFlowM, lrAtanh5Upper, lrAtanh5, lrLowShapeX, lrLowA, lrLowT,
    Finset.sum_range_succ]

theorem lrLowL1Minorant_edge_nonneg
    {v : ℝ} (hv : v ∈ Ioc (0 : ℝ) 1) :
    0 ≤ lrLowL1Minorant v lrLowShapeX := by
  have hvClosed : v ∈ Icc (0 : ℝ) 1 := ⟨hv.1.le, hv.2⟩
  have hbern := lrLowL1EndpointBernstein_nonneg hvClosed
  have hfactor : 0 ≤ 1 - v := sub_nonneg.mpr hv.2
  have hid := lrLowL1_endpoint_difference_identity hv
  have hprod : 0 ≤
      (lrLowL1Minorant v lrLowShapeX -
        lrLowL1Minorant 1 lrLowShapeX) *
          lrLowL1Base v * lrLowL1Base 1 := by
    rw [hid]
    exact mul_nonneg hfactor hbern
  have hbaseV : 0 < lrLowL1Base v := by
    unfold lrLowL1Base
    exact mul_pos (pow_pos (by linarith [hv.1]) _)
      (pow_pos (by linarith [hv.1]) _)
  have hbaseOne : 0 < lrLowL1Base 1 := by norm_num [lrLowL1Base]
  have hdiff : 0 ≤
      lrLowL1Minorant v lrLowShapeX -
        lrLowL1Minorant 1 lrLowShapeX := by
    have hwithoutOne := nonneg_of_mul_nonneg_left hprod hbaseOne
    exact nonneg_of_mul_nonneg_left hwithoutOne hbaseV
  linarith [lrLowL1Minorant_one_edge_pos]

theorem lrLowL1Minorant_nonneg
    {v x : ℝ} (hv : v ∈ Ioc (0 : ℝ) 1)
    (hx : x ∈ Icc (0 : ℝ) lrLowShapeX) :
    0 ≤ lrLowL1Minorant v x :=
  (lrLowL1Minorant_edge_nonneg hv).trans
    (lrLowL1Minorant_edge_le hv hx)

/-- The first scalar in the low-shape `U` reduction is now closed for every
positive coefficient index. -/
theorem lrLowLambda_actual_nonneg
    {v t : ℝ} (hv : v ∈ Ioo (0 : ℝ) 1)
    (ht : t ∈ Ioc (0 : ℝ) 1)
    (hshape : t ^ 2 ≤ lrLowShapeX) {n : ℕ} (hn : 1 ≤ n) :
    0 ≤ lrLowLambda v (t ^ 2) (lrGShape t v) n := by
  have hvIoc : v ∈ Ioc (0 : ℝ) 1 := ⟨hv.1, hv.2.le⟩
  have hx : t ^ 2 ∈ Icc (0 : ℝ) lrLowShapeX :=
    ⟨sq_nonneg t, hshape⟩
  have hone := lrLowLambda_one_nonneg_of_minorant hv ht
    (lrLowL1Minorant_nonneg hvIoc hx)
  apply lrLowLambda_nonneg_of_one hvIoc
    (show t ^ 2 ∈ Icc (0 : ℝ) (17 / 20) by
      simpa [lrLowShapeX] using hx) hone hn

end CourtadeKumar
