#!/usr/bin/env python3
"""Generate the exact Lean coefficient table for the TOP cap certificate.

The source verifier reconstructs the polynomial from the formulas in the
manuscript.  This generator repeats all of its exact checks before emitting a
48-by-61 Lean table of nonnegative rationals; it never uses floating-point
arithmetic.
"""

from __future__ import annotations

from fractions import Fraction
from hashlib import sha256
from pathlib import Path
import importlib.util
import sys


REPO = Path(__file__).resolve().parents[1]
SOURCE = (
    REPO.parent
    / "output/Courtade_Kumar_Proof_Package_2026-08-23/verification/programs"
    / "verify_full_cap_bernstein_closure.py"
)
TARGET = REPO / "InformationTheory/CourtadeKumar/TopCertificateData.lean"
EXPANDED_TARGET = REPO / "InformationTheory/CourtadeKumar/TopCertificateExpanded.lean"


def load_verifier():
    spec = importlib.util.spec_from_file_location("top_certificate_verifier", SOURCE)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load {SOURCE}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def lean_rat(q: Fraction) -> str:
    if q.denominator == 1:
        return str(q.numerator)
    numerator = f"({q.numerator})" if q.numerator < 0 else str(q.numerator)
    return f"mkRat {numerator} {q.denominator}"


def lean_nnrat(q: Fraction) -> str:
    assert q >= 0
    if q.denominator == 1:
        return str(q.numerator)
    return f"mkNNRat {q.numerator} {q.denominator}"


def lean_real_rat(q: Fraction) -> str:
    if q == 0:
        return "0"
    if q.denominator == 1:
        return f"({q.numerator} : ℝ)"
    return f"(({q.numerator} : ℝ) / {q.denominator})"


def horner(coefficients: list[Fraction], variable: str) -> str:
    last = max((i for i, q in enumerate(coefficients) if q != 0), default=0)
    value = lean_real_rat(coefficients[last])
    for q in reversed(coefficients[:last]):
        value = f"({lean_real_rat(q)} + {variable} * ({value}))"
    return value


def balanced_sum(terms: list[str]) -> str:
    if not terms:
        return "0"
    current = terms
    while len(current) > 1:
        current = [
            f"({current[i]} + {current[i + 1]})" if i + 1 < len(current) else current[i]
            for i in range(0, len(current), 2)
        ]
    return current[0]


def main() -> None:
    verifier = load_verifier()
    poly, _, _, _ = verifier.build_certificate()
    native = verifier.native_bernstein(poly)
    elevated = verifier.elevate_z(native, 22, 60)
    flat = [value for row in elevated for value in row]

    assert len(flat) == 48 * 61
    assert all(value >= 0 for value in flat)
    assert sum(value == 0 for value in flat) == 45
    positives = [
        (value, i, j)
        for i in range(48)
        for j in range(61)
        if (value := elevated[i][j]) > 0
    ]
    assert min(positives) == (Fraction(3174973, 1518982002412875), 47, 9)

    serialized = ";".join(
        f"{value.numerator}/{value.denominator}" for value in flat
    )
    assert sha256(serialized.encode()).hexdigest() == (
        "b76496233d695c6ed280b96d18fd9fc5fb3fee5013cc0848fa87834956646144"
    )

    elevated_rows = []
    for i in range(48):
        row = flat[i * 61 : (i + 1) * 61]
        row_lines = [
            "    " + ", ".join(map(lean_nnrat, row[j : j + 4]))
            for j in range(0, 61, 4)
        ]
        elevated_rows.append(
            f"def topElevatedBernsteinRowData{i} : Array ℚ≥0 :=\n"
            + "  #[\n" + ",\n".join(row_lines) + "\n  ]"
        )
    elevated_row_defs = "\n\n".join(elevated_rows)
    elevated_payload = ",\n    ".join(
        f"topElevatedBernsteinRowData{i}" for i in range(48)
    )

    power_flat = []
    for i in range(48):
        for j in range(23):
            value = verifier.sp.Rational(poly.coeff_monomial(verifier.C**i * verifier.Z**j))
            power_flat.append(Fraction(int(value.p), int(value.q)))
    assert len(power_flat) == 48 * 23
    assert sum(value != 0 for value in power_flat) == 918
    power_rows = []
    for i in range(48):
        row = power_flat[i * 23 : (i + 1) * 23]
        power_rows.append(
            f"def topCertificatePowerRowData{i} : Array ℚ :=\n"
            + "  #[" + ", ".join(map(lean_rat, row)) + "]"
        )
    power_row_defs = "\n\n".join(power_rows)
    power_payload = ",\n    ".join(
        f"topCertificatePowerRowData{i}" for i in range(48)
    )

    text = f'''import InformationTheory.CourtadeKumar.BernsteinCertificate

/-! This file is generated by `scripts/generate_top_bernstein_data.py` from
the exact full-cap replay.  Its 2,928 rationals have SHA-256 digest
`b76496233d695c6ed280b96d18fd9fc5fb3fee5013cc0848fa87834956646144` in the
serialization specified by the audited manuscript. -/

namespace CourtadeKumar

set_option maxRecDepth 100000

def mkNNRat (n d : ℕ) : ℚ≥0 := n / d

{elevated_row_defs}

def topElevatedBernsteinData : Array (Array ℚ≥0) :=
  #[{elevated_payload}]

theorem topElevatedBernsteinData_size :
    topElevatedBernsteinData.size = 48 ∧
      ∀ row ∈ topElevatedBernsteinData, row.size = 61 := by
  decide

def topElevatedBernsteinCoeff (i : Fin 48) (j : Fin 61) : ℚ :=
  (((topElevatedBernsteinData[i.val]?).getD #[])[j.val]?).getD 0

theorem topElevatedBernsteinCoeff_nonneg :
    ∀ i j, 0 ≤ topElevatedBernsteinCoeff i j := by
  intro i j
  exact NNRat.coe_nonneg _

theorem topElevatedBernsteinCoeff_minimum_witness :
    topElevatedBernsteinCoeff ⟨47, by omega⟩ ⟨9, by omega⟩ =
      3174973 / 1518982002412875 := by
  norm_num [topElevatedBernsteinCoeff, topElevatedBernsteinData,
    topElevatedBernsteinRowData47, mkNNRat]

{power_row_defs}

def topCertificatePowerData : Array (Array ℚ) :=
  #[{power_payload}]

theorem topCertificatePowerData_size :
    topCertificatePowerData.size = 48 ∧
      ∀ row ∈ topCertificatePowerData, row.size = 23 := by
  native_decide

def topCertificatePowerCoeffRat (i : Fin 48) (j : Fin 61) : ℚ :=
  if hj : j.val < 23 then
    (((topCertificatePowerData[i.val]?).getD #[])[j.val]?).getD 0
  else 0

def topCertificatePowerCoeffRatNat (i j : ℕ) : ℚ :=
  if hi : i < 48 then
    if hj : j < 61 then
      topCertificatePowerCoeffRat ⟨i, hi⟩ ⟨j, hj⟩
    else 0
  else 0

set_option maxHeartbeats 10000000 in
theorem topBernsteinPowerCoeff_eq_certificate :
    ∀ i : Fin 48, ∀ j : Fin 61,
      tensorBernsteinPowerCoeff
          (p := fun a b ↦ topElevatedBernsteinCoeff a b) i.val j.val =
        topCertificatePowerCoeffRat i j := by
  native_decide

end CourtadeKumar
'''
    TARGET.write_text(text)
    expanded_rows = []
    row_theorems = []
    for i in range(48):
        row_terms = []
        for j in range(23):
            q = power_flat[i * 23 + j]
            if q == 0:
                continue
            factors = [lean_real_rat(q)]
            if j:
                factors.append(f"z ^ {j}")
            row_terms.append(" * ".join(factors))
        row_value = balanced_sum(row_terms)
        expanded_rows.append(
            f"noncomputable def topCertificatePowerRowExpanded{i} (z : ℝ) : ℝ :=\n"
            f"  {row_value}"
        )
        row_theorems.append(
            f'''set_option maxHeartbeats 2000000 in
theorem topCertificatePowerRowEval{i} (c z : ℝ) :
    (∑ j ∈ Finset.range 61,
      (topCertificatePowerCoeffRatNat {i} j : ℝ) *
        c ^ {i} * z ^ j) =
      topCertificatePowerRowExpanded{i} z * c ^ {i} := by
  classical
  norm_num [topCertificatePowerCoeffRatNat, topCertificatePowerCoeffRat,
    topCertificatePowerData,
    topCertificatePowerRowData{i}, topCertificatePowerRowExpanded{i},
    Finset.sum_range_succ] <;> ring'''
        )
    expanded_row_defs = "\n\n".join(expanded_rows)
    row_theorem_text = "\n\n".join(row_theorems)
    row_dispatch = "\n".join(
        f"  | {i} => topCertificatePowerRowExpanded{i} z" for i in range(48)
    )
    generic_row_cases = "\n".join(
        f"  · simpa [topCertificatePowerRowExpanded] using "
        f"topCertificatePowerRowEval{i} c z"
        for i in range(48)
    )
    outer_terms = [
        f"topCertificatePowerRowExpanded{i} z * c ^ {i}" for i in range(48)
    ]
    value = balanced_sum(outer_terms)
    expanded_text = f'''import InformationTheory.CourtadeKumar.TopCertificateData

/-! Generated balanced evaluation of the exact 48-by-23 power coefficient
table.  This is an evaluation view of the same rationals checked in
`TopCertificateData`; it contains no floating-point constants. -/

namespace CourtadeKumar

open scoped BigOperators

{expanded_row_defs}

noncomputable def topCertificatePowerExpanded (c z : ℝ) : ℝ :=
  {value}

{row_theorem_text}

noncomputable def topCertificatePowerRowExpanded (i : ℕ) (z : ℝ) : ℝ :=
  match i with
{row_dispatch}
  | _ => 0

theorem topCertificatePowerRowEval (i : ℕ) (hi : i < 48) (c z : ℝ) :
    (∑ j ∈ Finset.range 61,
      (topCertificatePowerCoeffRatNat i j : ℝ) * c ^ i * z ^ j) =
      topCertificatePowerRowExpanded i z * c ^ i := by
  interval_cases i
{generic_row_cases}

set_option maxHeartbeats 2000000 in
theorem topCertificatePowerExpanded_eq_sum (c z : ℝ) :
    topCertificatePowerExpanded c z =
      ∑ i ∈ Finset.range 48, topCertificatePowerRowExpanded i z * c ^ i := by
  unfold topCertificatePowerExpanded
  norm_num [topCertificatePowerRowExpanded, Finset.sum_range_succ]
  ring

end CourtadeKumar
'''
    EXPANDED_TARGET.write_text(expanded_text)
    print(f"wrote {TARGET} ({len(flat)} exact coefficients)")
    print(f"wrote {EXPANDED_TARGET} (balanced exact power form)")


if __name__ == "__main__":
    main()
