#!/usr/bin/env python3
"""Generate the exact Lean coefficient table for the TOP cap certificate.

The source verifier reconstructs the polynomial from the formulas in the
manuscript.  This generator repeats all of its exact checks before emitting a
Lean `Vector Rat 2928`; it never uses floating-point arithmetic.
"""

from __future__ import annotations

from fractions import Fraction
from hashlib import sha256
from pathlib import Path
import importlib.util
import sys


REPO = Path(__file__).resolve().parents[1]
SOURCE = (
    REPO.parent
    / "output/Courtade_Kumar_Proof_Package_2026-08-23/verification/programs"
    / "verify_full_cap_bernstein_closure.py"
)
TARGET = REPO / "InformationTheory/CourtadeKumar/TopCertificateData.lean"


def load_verifier():
    spec = importlib.util.spec_from_file_location("top_certificate_verifier", SOURCE)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load {SOURCE}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def lean_rat(q: Fraction) -> str:
    if q.denominator == 1:
        return str(q.numerator)
    return f"mkRat {q.numerator} {q.denominator}"


def main() -> None:
    verifier = load_verifier()
    poly, _, _, _ = verifier.build_certificate()
    native = verifier.native_bernstein(poly)
    elevated = verifier.elevate_z(native, 22, 60)
    flat = [value for row in elevated for value in row]

    assert len(flat) == 48 * 61
    assert all(value >= 0 for value in flat)
    assert sum(value == 0 for value in flat) == 45
    positives = [
        (value, i, j)
        for i in range(48)
        for j in range(61)
        if (value := elevated[i][j]) > 0
    ]
    assert min(positives) == (Fraction(3174973, 1518982002412875), 47, 9)

    serialized = ";".join(
        f"{value.numerator}/{value.denominator}" for value in flat
    )
    assert sha256(serialized.encode()).hexdigest() == (
        "b76496233d695c6ed280b96d18fd9fc5fb3fee5013cc0848fa87834956646144"
    )

    rows = []
    for start in range(0, len(flat), 4):
        rows.append("    " + ", ".join(map(lean_rat, flat[start : start + 4])))
    payload = ",\n".join(rows)

    text = f'''import InformationTheory.CourtadeKumar.BernsteinCertificate

/-! This file is generated by `scripts/generate_top_bernstein_data.py` from
the exact full-cap replay.  Its 2,928 rationals have SHA-256 digest
`b76496233d695c6ed280b96d18fd9fc5fb3fee5013cc0848fa87834956646144` in the
serialization specified by the audited manuscript. -/

namespace CourtadeKumar

set_option maxRecDepth 100000

def topElevatedBernsteinData : Array ℚ :=
  #[
{payload}
  ]

theorem topElevatedBernsteinData_size :
    topElevatedBernsteinData.size = 2928 := by
  native_decide

def topElevatedBernsteinCoeff (i : Fin 48) (j : Fin 61) : ℚ :=
  (topElevatedBernsteinData[i.val * 61 + j.val]?).getD 0

theorem topElevatedBernsteinCoeff_nonneg :
    ∀ i j, 0 ≤ topElevatedBernsteinCoeff i j := by
  native_decide

theorem topElevatedBernsteinCoeff_minimum_witness :
    topElevatedBernsteinCoeff ⟨47, by omega⟩ ⟨9, by omega⟩ =
      3174973 / 1518982002412875 := by
  native_decide

end CourtadeKumar
'''
    TARGET.write_text(text)
    print(f"wrote {TARGET} ({len(flat)} exact coefficients)")


if __name__ == "__main__":
    main()
